// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxdWIMDaqKC1FSzGZu3--zbi3ZojrS9nE',
    appId: '1:64548452550:web:6e99d651e2c382134b7fc7',
    messagingSenderId: '64548452550',
    projectId: 'test-project-d51fa',
    authDomain: 'test-project-d51fa.firebaseapp.com',
    storageBucket: 'test-project-d51fa.appspot.com',
    measurementId: 'G-JGNH3GZ6N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAzv26qNy5xjm1N3MorH2hHQZlF2Fv6nA',
    appId: '1:64548452550:android:d5312c893a85470c4b7fc7',
    messagingSenderId: '64548452550',
    projectId: 'test-project-d51fa',
    storageBucket: 'test-project-d51fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhGxuBSNjce1JlH2r0SPoKn75pmKLsiUk',
    appId: '1:64548452550:ios:7990c96893ef231e4b7fc7',
    messagingSenderId: '64548452550',
    projectId: 'test-project-d51fa',
    storageBucket: 'test-project-d51fa.appspot.com',
    iosClientId: '64548452550-65i70c2gi57ju9pg6rucs7qlq8ae9qlb.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhGxuBSNjce1JlH2r0SPoKn75pmKLsiUk',
    appId: '1:64548452550:ios:1ed46d65d0f57d744b7fc7',
    messagingSenderId: '64548452550',
    projectId: 'test-project-d51fa',
    storageBucket: 'test-project-d51fa.appspot.com',
    iosClientId: '64548452550-jc1s41t1b7j9c4fdlf5hv430estb9qb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest.RunnerTests',
  );
}
